# Examples

## Don't Be Tricked

::: {.rmdthink}

1. A pizza shop sales 12-inches pizza and 8-inches pizza at the price \$12/each and \$6/each respectively.  With \$12, would you like to order one 12-inches and two 8-inches. Why?

2. A sheet of everyday copy paper is about 0.01 millimeter thick. Repeat folding along a different side 20 times. Now, how thick do you think the folded paper is?

:::

## Properties of Exponents

For an integer $n$, and an expression $x$, the mathematical operation of the $n$-times repeated multiplication of $x$  is call exponentiation, written as $x^n$, that is,
$$
x^n=\underbrace{x\cdot x \cdots x}_{n~\text{factors of}~x}.
$$

In the notation $x^n$, $n$ is called ***the exponent***, $x$ is called ***the base***, and $x^n$ is called ***the power***, read as "$x$ raised to the $n$-th power",  "$x$ to the $n$-th power", "$x$ to the $n$-th", "$x$ to the power of $n$" or "$x$ to the $n$".

| Property | Example|
|---|---|
|The product rule $$x^m\cdot x^n=x^{m+n}.$$ | $$2x^2\cdot (-3x^3)=-6x^5.$$ |
| The quotient rule (for $x\neq 0$.) $$\dfrac{x^m}{x^n}= \begin{cases} x^{m-n}  & \text{if} m\ge n.\\[1em] \dfrac{1}{x^{n-m}} & \text{if} m\le n. \end{cases} $$ | $$\frac{15x^5}{5x^2}=3x^3;$$ $$\frac{-3x^2}{6x^3}=-\frac{1}{2x}.$$ |
| The zero exponent rule (for $x\neq 0$.) $$x^0=1.$$ | $$(-2)^0=1;$$ $$-x^0=-1.$$ |
| The negative exponent rule (for $x\neq 0$.) $$x^{-n}=\dfrac{1}{x^n} \quad\text{and}\quad \dfrac{1}{x^{-n}}=x^n.$$ | $$(-2)^{-3}=\frac{1}{(-2)^3}=-\frac18;$$ $$\frac{x^{-2}}{x^{-3}}=\frac{x^3}{x^2}=x.$$ |
| The power to a power rule $$\left(x^a\right)^b=x^{ab}.$$ | $$\left(2^{2}\right)^3=2^6=64;$$ $$\left(x^2\right)^3=x^6.$$ |
| The product raised to a power rule $$(xy)^n=x^ny^n.$$ | $$\left(-2x\right)^{2}=(-2)^2x^2=4x^2.$$ |
| The quotient raised to a power rule (for $y\neq 0$.) $$\left(\dfrac{x}{y}\right)^n=\dfrac{x^n}{y^n}.$$ | $$    \left(\dfrac{x}{-2}\right)^{3}=\dfrac{x^3}{(-2)^3}=-\dfrac{x^3}{8}.$$ |

::: {.rmdnote}

**Order of Basic Mathematical Operations**  

In mathematics, the order of operations reflects conventions about which procedure should be performed first. There are four levels (from the highest to the lowest):

**Parenthesis**; **Exponentiation**; **Multiplication and Division**; **Addition and Subtraction**.  

Within the same level, the convention is to perform from the left to the right.

:::

```{example}

Simplify. **Write with positive exponents.**
$$
\left(\dfrac{2y^{-2}z^{-5}}{4x^{-3}y^6}\right)^{-4}.
$$

```

```{solution}

The idea is to simplify the base first and rewrite using positive exponents only.

$$
\begin{aligned}
    \left(\dfrac{2y^{-2}z^{-5}}{4x^{-3}y^6}\right)^{-4}
=&\left(\dfrac{x^3}{2z^{5}y^8}\right)^{-4}\\
=&\left(\dfrac{2z^{5}y^8}{x^3}\right)^4\\
=&\dfrac{2^4(z^{5})^4(y^8)^4}{(x^3)^4}\\
=&\dfrac{16y^{32}z^{20}}{x^{12}}.\\
\end{aligned}
$$

```

::: {.rmdtip}

**Simplify (at least partially) the problem first**  
To avoid mistakes when working with negative exponents, it's better to apply the negative exponent rule to change negative exponents to positive exponents and simplify the base first.

:::

\newpage

## Generating Theorem Environments Using R Bookdown Code Chunks

Bookdown theorem environments work great. It will be awesome if it can handle r code chunks within a theorem block.

```{theorem, name="Pythagorean Theorem"}

If $c$ denotes the length of the hypotenuse and $a$ and $b$ denote the lengths of the other two sides, the Pythagorean theorem can be expressed as the Pythagorean equation:
$$a^2+b^2=c^2.$$

```

```{corollary}

For any angle $\theta$, we have
$$
\sin^2\theta+\cos^2\theta=1
$$

```

```{lemma}

For any angle $\theta$, projecting the terminal side to the $x$-axis forms a right triangle.

```

\newpage

## Generating Theorem Environments Using Pandoc Fence Code Blocks

Bookdown has a lua filter called "latex-div.lua" which handles theorem environments for latex.

::: {.theorem data-latex="Pythagorean Theorem"}

**No Theorem Name Displayed**  
If $c$ denotes the length of the hypotenuse and $a$
 and $b$ denote the lengths of the other two sides,
 the Pythagorean theorem can be expressed as the Pythagorean equation:
$$a^2+b^2=c^2.$$

:::

::: {.corollary data-latex=""}

For any angle $\theta$, we have
$$
\sin^2\theta+\cos^2\theta=1
$$

:::

::: {.lemma data-latex="Pandoc Div Blocks"}

Pandoc use `::: {#Id .Div_attributes}` to start and `:::`
 to end a Div block. Such a block can be converted
  to LaTeX environment using lua.

:::

The codes for the above three environments are in the following

```Rmarkdown

::: {.theorem data-latex="Pythagorean Theorem"}
**No Theorem Name Displayed**  
If $c$ denotes the length of the hypotenuse and $a$ and $b$
 denote the lengths of the other two sides,
  the Pythagorean theorem can be expressed as
   the Pythagorean equation:
$$a^2+b^2=c^2.$$

:::

::: {.corollary data-latex=""}

For any angle $\theta$, we have
$$
\sin^2\theta+\cos^2\theta=1
$$

:::

::: {.lemma data-latex="Pandoc Div Blocks"}

Pandoc use `::: {#Id .Div_attributes}` to start
 and `:::` to end a Div block.
  Such a block can be converted to LaTeX environment using lua.

:::


```

\newpage

## Practice

```{exercise}

Simplify. **Write with positive exponents.**

1. $(3a^2b^3c^2)(4abc^2)(2b^2c^3)$
2. $\dfrac{4y^3z^0}{x^2y^2}$
3. $(-2)^{-3}$

```

```{exercise}

Simplify. **Write with positive exponents.**

1. $\dfrac{-u^0v^{15}}{v^{16}}$
1. $(-2a^3b^2c^0)^3$
1. $\dfrac{m^5 n^{2}}{(mn)^3}$

```

```{exercise}

Simplify. **Write with positive exponents.**

1. $(-3a^2x^3)^{-2}$
1. $\left(\dfrac{-x^0y^3}{2wz^2}\right)^3$
1. $\dfrac{3^{-2}a^{-3}b^5}{x^{-3}y^{-4}}$

```

```{exercise}

Simplify. **Write with positive exponents.**

1. $\left(-x^{-1}(-y)^2\right)^3$
2. $\left(\dfrac{6x^{-2}y^5}{2y^{-3}z^{-11}}\right)^{-3}$
3. $\dfrac{(3 x^{2} y^{-1})^{-3}(2 x^{-3} y^{2})^{-1}}{(x^{6} y^{-5})^{-2}}$

```

```{exercise}

A store has large size and small size watermelons. A large one cost \$4 and a small one \$1. Putting on the same table, a smaller watermelons has only half the height of the larger one. Given \$4, will you buy a large watermelon or 4 smaller ones? Why?

```
